spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  application:
    name: panchoSpring
  #jpa:
  #  database: mysql
  #  show-sql: true
  #  hibernate:
  #    ddl-auto: create
  #datasource:
  #  url: jdbc:mysql://localhost:3306/cuidando_a_pancho
  #  username: root
  #  password:
  #  driver-class-name: com.mysql.cj.jdbc.Driver
  #data:
  #  jdbc:
  #    dialect: mysql
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

